version: '3.8'

services:
  mongo:
    image: mongo
    container_name: mylist-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  mongo-express:
    image: mongo-express
    container_name: mylist-mongo-express
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=admin
    depends_on:
      - mongo

  app:
    build:
      context: .
      dockerfile: DockerFile
    container_name: mylist-app
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/mylist
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - mongo
    command: npx ts-node-dev src/index.ts

volumes:
  mongo_data:
